"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""

def even_fib():
    i, a = 1, 0
    nums = []
    while i < 4e6:
        if i % 2 == 0:
            nums.append(i)
        a, i = i, i + a
    print(sum(nums))

even_fib()